version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: django.Dockerfile
    command: uvicorn dcrm.asgi:application --host 0.0.0.0 --port 8000
    environment:
      - DB_URL=postgresql://dbuser:pass123@db/foo
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=foo
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.http.config:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  postgres_data: